"use server";
import { revalidatePath } from 'next/cache'; import { redirect } from 'next/navigation'; import { createClient } from '@/lib/supabase/server'; import { requirePermission } from '@/lib/auth/authorize'; import { auditAction } from '@/lib/audit'; import { sponsorSchema } from '@/lib/validation/sponsors';
const v=(x:FormDataEntryValue|null)=>typeof x==='string'?x.trim():'';
export async function getSponsors(){await requirePermission('sponsors.view');const {data,error}=await (await createClient()).from('sponsors').select('*').is('deleted_at',null).order('sort_order').order('created_at');if(error)throw new Error(error.message);return data??[]}
function input(fd:FormData){return sponsorSchema.parse({name:v(fd.get('name')),tier:v(fd.get('tier')),logo:v(fd.get('logo'))||null,url:v(fd.get('url'))||null,sortOrder:fd.get('sortOrder')||0,published:fd.get('published')??true})}
export async function addSponsor(fd:FormData){const a=await requirePermission('sponsors.create');const i=input(fd);const {data,error}=await (await createClient()).from('sponsors').insert({name:i.name,tier:i.tier,logo:i.logo,url:i.url,sort_order:i.sortOrder,published:i.published}).select('*').single();if(error)throw new Error(error.message);await auditAction({actorId:a.id,action:'SPONSOR_CREATED',entityType:'Sponsor',entityId:data.id,metadata:{name:data.name}});revalidatePath('/');revalidatePath('/admin/sponsors');redirect('/admin/sponsors?success=true')}
export async function updateSponsor(id:string,fd:FormData){const a=await requirePermission('sponsors.edit');const i=input(fd);const {error}=await (await createClient()).from('sponsors').update({name:i.name,tier:i.tier,logo:i.logo,url:i.url,sort_order:i.sortOrder,published:i.published}).eq('id',id);if(error)throw new Error(error.message);await auditAction({actorId:a.id,action:'SPONSOR_UPDATED',entityType:'Sponsor',entityId:id,metadata:{name:i.name}});revalidatePath('/');revalidatePath('/admin/sponsors');redirect('/admin/sponsors?success=true')}
export async function deleteSponsor(id:string){const a=await requirePermission('sponsors.delete');const s=await createClient();const {data:row}=await s.from('sponsors').select('name').eq('id',id).maybeSingle();if(!row)return;const {error}=await s.from('sponsors').update({deleted_at:new Date().toISOString(),published:false}).eq('id',id);if(error)throw new Error(error.message);await auditAction({actorId:a.id,action:'SPONSOR_DELETED',entityType:'Sponsor',entityId:id,metadata:{name:row.name}});revalidatePath('/');revalidatePath('/admin/sponsors')}
export const addDummySponsor=addSponsor;
